# Generated by Django 5.2.8 on 2026-07-19 06:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAccountingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(max_length=10)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=255)),
                ('project_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subcategory_name', models.CharField(max_length=255)),
                ('wallet_flow', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_code', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('synced', models.BooleanField(default=False)),
                ('sync_attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_request_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unallocated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_desc', models.TextField(blank=True, null=True)),
                ('raw_callback', models.JSONField(blank=True, null=True)),
                ('selected_orders', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('STK_SENT', 'STK Sent'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PROCESSING', 'Processing Orders'), ('PROCESSED', 'Processed'), ('EXTRA_PAID', 'Extra Paid')], default='PENDING', max_length=20)),
                ('processed', models.BooleanField(default=False)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
            ],
        ),
    ]
