# Generated by Django 5.2.8 on 2026-07-30 03:31

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('delivery_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_used', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_used_phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('transport_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('SENT', 'Sent'), ('ON_ROAD', 'On Road'), ('ARRIVED', 'Arrived'), ('PICKED', 'Picked')], default='OPEN', max_length=10)),
                ('all_luggages_picked', models.BooleanField(default=False)),
                ('arrived_at_the_receiving_agent', models.BooleanField(default=False)),
                ('date_arrived_at_the_receiving_agent', models.DateTimeField(blank=True, help_text='date parcel arrived to the destination', null=True)),
                ('date_picked_by_the_receiving_agent', models.DateTimeField(blank=True, help_text='from the courior company', null=True)),
                ('dispatch_send', models.BooleanField(default=False, help_text='send by the sending agent')),
                ('date_send', models.DateTimeField(blank=True, help_text='date send by the sending agent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_dispatches', to='agents.agent')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_dispatch_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PackageDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('receiver_identification_code', models.UUIDField()),
                ('total_transport_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('fully_paid', models.BooleanField(default=False)),
                ('fully_paid_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('SENT', 'Sent'), ('ON_ROAD', 'On Road'), ('ARRIVED', 'Arrived'), ('PICKED', 'Picked')], default='OPEN', max_length=10)),
                ('arrived_at_the_sending_agent', models.BooleanField(default=False)),
                ('date_arrived_at_the_sending_agent', models.DateTimeField(blank=True, null=True)),
                ('packed_by_the_sending_agent', models.BooleanField(default=False)),
                ('date_packed_by_the_sending_agent', models.DateTimeField(blank=True, null=True)),
                ('picked_picked_by_receiving_customer', models.BooleanField(default=False, help_text='picked at the receiving agent')),
                ('date_picked_picked_by_receiving_customer', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('agent_dispatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_dispatches', to='logistics.agentdispatch')),
                ('packed_by', models.ForeignKey(blank=True, help_text='the person that packed the package at the sending agent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packing_staff', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(blank=True, help_text='the person that received the package at the sending agent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving_staff', to=settings.AUTH_USER_MODEL)),
                ('receiving_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving_agent', to='agents.agent')),
                ('receiving_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving_customer', to='customers.customer')),
                ('sending_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sending_agent', to='agents.agent')),
                ('sending_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sending_customer', to='customers.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('envelope', 'Envelope'), ('box', 'Box'), ('sack', 'Sack'), ('uhuru_bag', 'Uhuru Bag'), ('cylinder', 'Cylinder'), ('other', 'Other')], max_length=20)),
                ('package_color', models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('blue', 'Blue'), ('green', 'Green'), ('brown', 'Brown'), ('grey', 'Grey'), ('maroon', 'Maroon'), ('orange', 'Orange'), ('pink', 'Pink'), ('purple', 'Purple'), ('red', 'Red'), ('yellow', 'Yellow'), ('branded', 'Branded')], max_length=20, null=True)),
                ('weight', models.CharField(choices=[('2', '0 - 2 Kg'), ('5', '1 - 5 Kg'), ('10', '5 - 10 Kg'), ('20', '10 - 20 Kg'), ('50', '20 - 50 Kg'), ('50+', 'Above 50 Kg')], max_length=20)),
                ('volume', models.CharField(blank=True, choices=[('0.05', '0 - 0.05 m³'), ('0.1', '0.05 - 0.1 m³'), ('0.25', '0.1 - 0.25 m³'), ('0.5', '0.25 - 0.5 m³'), ('1', '0.5 - 1 m³'), ('1+', 'Above 1 m³')], max_length=20, null=True)),
                ('contents', models.CharField(help_text='E.g. Shoes, Clothes, Electronics', max_length=255)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity', models.IntegerField(default=1)),
                ('is_fragile', models.BooleanField(default=False)),
                ('is_spill_prone', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, help_text='Additional package details, quantities, variations, etc.', null=True)),
                ('transport_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='logistics.packagedispatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('GENERAL', 'General'), ('PACKING', 'Packing'), ('TRANSPORT', 'Transport'), ('DELIVERY', 'Delivery'), ('PAYMENT', 'Payment')], default='GENERAL', max_length=20)),
                ('note', models.TextField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='logistics.packagedispatch')),
            ],
        ),
    ]
