# Generated by Django 5.2.8 on 2026-07-19 06:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('delivery_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_used', models.CharField(blank=True, max_length=100, null=True)),
                ('vehicle_used_phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('transport_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('SENT', 'Sent'), ('ON_ROAD', 'On Road'), ('ARRIVED', 'Arrived'), ('PICKED', 'Picked')], default='OPEN', max_length=10)),
                ('date_arrived', models.DateTimeField(blank=True, null=True)),
                ('date_picked', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_dispatches', to='customers.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_dispatch_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('delivery_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('vehicle_used', models.CharField(blank=True, max_length=100, null=True)),
                ('approx_transport_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('packaging_bag_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('beba_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('SENT', 'Sent'), ('ON_ROAD', 'On Road'), ('ARRIVED', 'Arrived'), ('PICKED', 'Picked')], default='OPEN', max_length=10)),
                ('all_luggages_picked', models.BooleanField(default=False)),
                ('date_arrived', models.DateTimeField(blank=True, null=True)),
                ('date_picked', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('agent_dispatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_dispatches', to='logistics.agentdispatch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='customers.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDispatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manual_product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sender', models.CharField(blank=True, max_length=200, null=True)),
                ('sender_phone', models.CharField(blank=True, max_length=200, null=True)),
                ('sending_from', models.CharField(blank=True, max_length=200, null=True)),
                ('manual_product_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='approximate value', max_digits=12)),
                ('is_manual_product', models.BooleanField(default=False)),
                ('quantity_paid_for', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('quantity_packed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('ready_to_dispatch', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='logistics.customerdispatch')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('GENERAL', 'General'), ('PACKING', 'Packing'), ('TRANSPORT', 'Transport'), ('DELIVERY', 'Delivery'), ('PAYMENT', 'Payment')], default='GENERAL', max_length=20)),
                ('note', models.TextField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='logistics.customerdispatch')),
            ],
        ),
    ]
