# Generated by Django 5.2.8 on 2026-07-19 13:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('customers', '0002_receiver_sender_delete_inquiries_and_more'),
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdispatch',
            name='agent_dispatch',
        ),
        migrations.RemoveField(
            model_name='customerdispatch',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerdispatch',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='agentdispatch',
            name='all_luggages_picked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agentdispatch',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_dispatches', to='agents.agent'),
        ),
        migrations.CreateModel(
            name='PackageDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('delivery_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('total_transport_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('SENT', 'Sent'), ('ON_ROAD', 'On Road'), ('ARRIVED', 'Arrived'), ('PICKED', 'Picked')], default='OPEN', max_length=10)),
                ('date_arrived', models.DateTimeField(blank=True, null=True)),
                ('date_picked', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('agent_dispatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_dispatches', to='logistics.agentdispatch')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='customers.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('envelope', 'Envelope'), ('box', 'Box'), ('sack', 'Sack'), ('uhuru_bag', 'Uhuru Bag'), ('cylinder', 'Cylinder'), ('other', 'Other')], max_length=20)),
                ('package_color', models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('blue', 'Blue'), ('green', 'Green'), ('brown', 'Brown'), ('grey', 'Grey'), ('maroon', 'Maroon'), ('orange', 'Orange'), ('pink', 'Pink'), ('purple', 'Purple'), ('red', 'Red'), ('yellow', 'Yellow'), ('branded', 'Branded')], max_length=20, null=True)),
                ('weight', models.CharField(choices=[('2', '0 - 2 Kg'), ('5', '1 - 5 Kg'), ('10', '5 - 10 Kg'), ('20', '10 - 20 Kg'), ('50', '20 - 50 Kg'), ('50+', 'Above 50 Kg')], max_length=20)),
                ('volume', models.CharField(blank=True, choices=[('0.05', '0 - 0.05 m³'), ('0.1', '0.05 - 0.1 m³'), ('0.25', '0.1 - 0.25 m³'), ('0.5', '0.25 - 0.5 m³'), ('1', '0.5 - 1 m³'), ('1+', 'Above 1 m³')], max_length=20, null=True)),
                ('contents', models.CharField(help_text='E.g. Shoes, Clothes, Electronics', max_length=255)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_fragile', models.BooleanField(default=False)),
                ('is_spill_prone', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, help_text='Additional package details, quantities, variations, etc.', null=True)),
                ('transport_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='logistics.packagedispatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='dispatchnote',
            name='dispatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='logistics.packagedispatch'),
        ),
        migrations.DeleteModel(
            name='CustomerDispatchItem',
        ),
        migrations.DeleteModel(
            name='CustomerDispatch',
        ),
    ]
