# Generated by Django 5.2.8 on 2026-07-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagedispatch',
            name='receiver_identification_code',
            field=models.CharField(),
        ),
    ]
