# Generated by Django 5.2.8 on 2026-08-06 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('logistics', '0002_alter_packagedispatch_receiver_identification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='sending_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_sending_customer', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='packagedispatch',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('PACKED', 'Packed'), ('SENT', 'Sent'), ('ON_ROAD', 'On Road'), ('ARRIVED', 'Arrived'), ('PICKED', 'Picked')], default='OPEN', max_length=10),
        ),
    ]
