# Generated by Django 5.2.8 on 2026-07-20 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('customers', '0003_remove_sender_customer_delete_receiver_delete_sender'),
        ('logistics', '0002_remove_customerdispatch_agent_dispatch_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagedispatch',
            old_name='date_arrived',
            new_name='date_arrived_at_the_sending_agent',
        ),
        migrations.RenameField(
            model_name='packagedispatch',
            old_name='date_picked',
            new_name='date_packed_by_the_sending_agent',
        ),
        migrations.AddField(
            model_name='package',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='packagedispatch',
            name='arrived_at_the_sending_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='packagedispatch',
            name='date_picked_picked_by_receiving_customer',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packagedispatch',
            name='packed_by',
            field=models.ForeignKey(blank=True, help_text='the person that packed the package at the sending agent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packing_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packagedispatch',
            name='packed_by_the_sending_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='packagedispatch',
            name='picked_picked_by_receiving_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='packagedispatch',
            name='received_by',
            field=models.ForeignKey(blank=True, help_text='the person that received the package at the sending agent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packagedispatch',
            name='receiving_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving_agent', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='packagedispatch',
            name='receiving_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiving_customer', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='packagedispatch',
            name='sending_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sending_agent', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='packagedispatch',
            name='sending_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sending_customer', to='customers.customer'),
        ),
    ]
