# Generated by Django 5.2.8 on 2026-08-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_package_sending_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedispatch',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
