# Generated by Django 5.2.8 on 2026-07-20 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_rename_date_arrived_packagedispatch_date_arrived_at_the_sending_agent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagedispatch',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='packagedispatch',
            name='delivery_address',
        ),
    ]
