# Generated by Django 5.2.8 on 2026-07-21 03:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_remove_packagedispatch_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedispatch',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='packagedispatch',
            name='fully_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='packagedispatch',
            name='fully_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
