# Generated by Django 5.2.8 on 2026-08-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_packagedispatch_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='to_big',
            field=models.BooleanField(default=False, help_text='to big to be combined with other packages in one sack'),
        ),
    ]
