# Generated by Django 5.2.8 on 2026-08-09 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_package_to_big'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='packed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='packed_by',
            field=models.ForeignKey(blank=True, help_text='the person that packed the package at the sending agent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_packing_staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agentdispatch',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('SENT', 'Sent'), ('ON_ROAD', 'On Road'), ('ARRIVED', 'Arrived'), ('PICKED', 'All Picked')], default='OPEN', max_length=10),
        ),
    ]
