# Generated by Django 5.2.8 on 2026-07-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_packagedispatch_amount_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentdispatch',
            name='date_arrived',
        ),
        migrations.RemoveField(
            model_name='agentdispatch',
            name='date_picked',
        ),
        migrations.AddField(
            model_name='agentdispatch',
            name='arrived_at_the_receiving_agent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentdispatch',
            name='date_arrived_at_the_receiving_agent',
            field=models.DateTimeField(blank=True, help_text='date parcel arrived to the destination', null=True),
        ),
        migrations.AddField(
            model_name='agentdispatch',
            name='date_picked_by_the_receiving_agent',
            field=models.DateTimeField(blank=True, help_text='from the courior company', null=True),
        ),
        migrations.AddField(
            model_name='agentdispatch',
            name='date_send',
            field=models.DateTimeField(blank=True, help_text='date send by the sending agent', null=True),
        ),
        migrations.AddField(
            model_name='agentdispatch',
            name='dispatch_send',
            field=models.BooleanField(default=False, help_text='send by the sending agent'),
        ),
        migrations.AlterField(
            model_name='packagedispatch',
            name='picked_picked_by_receiving_customer',
            field=models.BooleanField(default=False, help_text='picked at the receiving agent'),
        ),
    ]
