# Generated by Django 5.2.8 on 2026-08-09 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_package_packed_package_packed_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packagedispatch',
            old_name='packed_by_the_sending_agent',
            new_name='packed_as_individual_by_the_sending_agent',
        ),
        migrations.AddField(
            model_name='packagedispatch',
            name='packed_as_combined_package_by_the_sending_agent',
            field=models.BooleanField(default=False, help_text='cobined together with other products heading to same agent'),
        ),
    ]
