# Generated by Django 5.2.8 on 2026-08-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_rename_packed_by_the_sending_agent_packagedispatch_packed_as_individual_by_the_sending_agent_and_mor'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedispatch',
            name='date_picked_picked_by_receiving_agent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='packagedispatch',
            name='picked_picked_by_receiving_agent',
            field=models.BooleanField(default=False, help_text='picked by the receiving agent'),
        ),
    ]
