# Generated by Django 5.2.8 on 2026-08-23 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_packagedispatch_date_picked_picked_by_receiving_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedispatch',
            name='loyalty_counted',
            field=models.BooleanField(default=False),
        ),
    ]
