# Generated by Django 5.2.8 on 2026-08-24 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('logistics', '0009_packagedispatch_loyalty_counted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdispatch',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_dispatches', to='agents.agent'),
        ),
        migrations.AlterField(
            model_name='packagedispatch',
            name='agent_dispatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_dispatches', to='logistics.agentdispatch'),
        ),
    ]
