# Generated by Django 5.2.8 on 2026-08-25 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_alter_agentdispatch_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedispatch',
            name='is_special_dispatch',
            field=models.BooleanField(default=False, help_text='This dispatch is reserved for a large, fragile, or spill-prone package.'),
        ),
    ]
