# Generated by Django 5.2.8 on 2026-08-25 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('logistics', '0011_packagedispatch_is_special_dispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdispatch',
            name='sending_agent',
            field=models.ForeignKey(blank=True, help_text='sending agent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sending_agent_dispatches', to='agents.agent'),
        ),
        migrations.AlterField(
            model_name='agentdispatch',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='receiving agent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_dispatches', to='agents.agent'),
        ),
    ]
