# Generated by Django 5.2.8 on 2026-08-27 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0012_agentdispatch_sending_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentdispatch',
            name='vehicle_used',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='agentdispatch',
            name='vehicle_used_phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='contents',
            field=models.CharField(help_text='E.g. Shoes, Clothes, Electronics', max_length=355),
        ),
        migrations.AlterField(
            model_name='packagedispatch',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='packagedispatch',
            name='delivery_phone',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
