# Generated by Django 5.2.8 on 2026-08-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0013_alter_agentdispatch_vehicle_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedispatch',
            name='sending_address',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
