# Generated by Django 5.2.8 on 2026-07-30 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='customer', max_length=250)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='customer-profiles')),
                ('phone_number', models.CharField(blank=True, max_length=25, null=True)),
                ('delivery_address', models.TextField(blank=True, null=True)),
                ('total_loyalty_points', models.IntegerField(default=0)),
                ('total_available_votes', models.IntegerField(default=10, help_text='this are vote slots that will be used to cast votes for others')),
                ('refferal_code', models.CharField(max_length=8, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('reffered_by', models.ForeignKey(blank=True, help_text='user who reffered customer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reffer', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScanCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date_scanned', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
            ],
        ),
    ]
