# Generated by Django 5.2.8 on 2026-07-20 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_receiver_sender_delete_inquiries_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sender',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Receiver',
        ),
        migrations.DeleteModel(
            name='Sender',
        ),
    ]
